### ISSUE TITLE
super expression must either be null or a function not undefined

### ISSUE THREAD

**Issue by pauldowlin** [larsvinter/react-native-awesome-button#12]
Was getting this error with react native build .26.3
Noticed that if I used the latest recommendations the error goes away.
This is inside AwesomeButton.js

`import React, { Component, } from 'react';`

`import {
   Animated,
   ActivityIndicatorIOS,
   View,
   Text,
   StyleSheet,
   TouchableOpacity
} from 'react-native';`

**Comment by seantempesta** [comment]
Thanks @pauldowlin!

**Comment by larsvinter** [comment]
Duplicate
