### ISSUE TITLE
Import Error!

### ISSUE THREAD

**Issue by jose920405** [larsvinter/react-native-awesome-button#13]
Just import
![screen shot 2016-06-29 at 8 22 10 am](https://cloud.githubusercontent.com/assets/12536184/16453491/9edd5996-3dd2-11e6-8965-ec42ecc6d235.png)

Show this error:
![simulator screen shot jun 29 2016 8 21 49 am](https://cloud.githubusercontent.com/assets/12536184/16453453/8914827e-3dd2-11e6-88f5-c66b28db2700.png)

**Comment by martypenner** [comment]
A PR is pending for this: https://github.com/larsvinter/react-native-awesome-button/pull/11. The maintainer seems unresponsive, though.

**Comment by larsvinter** [comment]
Had a problem with merging and my environment so couldn't test. Have tried to resolve them "in the blind" now. Will try to test asap.

**Comment by martypenner** [comment]
Awesome! Thanks for working on this.
