### ISSUE TITLE
Warning that  ProgressBarAndroid is deprecated

### ISSUE THREAD

**Issue by frangeris** [larsvinter/react-native-awesome-button#15]
Thank's for this pack, awesome :)

I'm receiving a warning:

``` bash
Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead.
```

Android 4.2.2
`"react-native": "^0.31.0",`
`"react": "^15.2.1",`

<img width="508" alt="screen shot 2016-08-16 at 9 44 25 pm" src="https://cloud.githubusercontent.com/assets/811381/17720735/ab25c26c-63fa-11e6-8d21-34321cd02213.png">

Is it time to upgrade the [src/ProgressBar.js](https://github.com/larsvinter/react-native-awesome-button/blob/8f5a58cc10a8b66948280f4d0ec26ca585f3a247/src/ProgressBar.js#L6)?

**Comment by CoteViande** [comment]
Deprecation removed ;)

**Comment by CoteViande** [comment]
#17
