### ISSUE TITLE
undefined is not an object (evaluating 'hex.replace')

### ISSUE THREAD

**Issue by Copypeng** [larsvinter/react-native-awesome-button#2]
When i use the AwesomeButton.js，The app crashed due to uncaught exception 'Unhandled JS Exception: undefined is not an object (evaluating 'hex.replace')'.

**Comment by larsvinter** [comment]
Hi. 

Did you specify your color in hex-format?
I have on the to-do to improve the function so it also accepts "white", "black" etc. or rgb format, but have not done this yet.

Lars

**Comment by Copypeng** [comment]
I see.Thanks a lot.
