### ISSUE TITLE
"spinner: true" causes build time error 

### ISSUE THREAD

**Issue by MiguelGrenho** [larsvinter/react-native-awesome-button#20]
Using the provided example code, when you set the spinner value to true, an error appears in iOS:

![simulator screen shot 17 feb 2017 14 35 12](https://cloud.githubusercontent.com/assets/5865757/23069160/4cfbe666-f51e-11e6-82e0-5cf21c848c6b.png)

**Comment by larsvinter** [comment]
Fixed in 1.7.0
