### ISSUE TITLE
Please remove your node_modules folder... 

### ISSUE THREAD

**Issue by harriswan9a** [larsvinter/react-native-awesome-button#21]
[Warning] Packager is not running
######### Executing command: react-native start --port 8081 --resetCache ##########
Scanning 756 folders for symlinks in /Users/harris/MyProject/ReactNative/react-native-iam/node_modules (10ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/harris/MyProject/ReactNative/react-native-iam 

[2017-02-24 23:57:01] <START> Initializing Packager
[2017-02-24 23:57:01]         HMR Server listening on /hot

React packager ready.

######### Packager started. ##########
jest-haste-map: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/harris/MyProject/ReactNative/react-native-iam/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/TouchHistoryMath.js collides with /Users/harris/MyProject/ReactNative/react-native-iam/node_modules/react-native-awesome-button/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/TouchHistoryMath.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: ResponderTouchHistoryStore
  Paths: /Users/1500089a/MyProject/ReactNative/react-native-iam/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/ResponderTouchHistoryStore.js collides with /Users/1500089a/MyProject/ReactNative/react-native-iam/node_modules/react-native-awesome-button/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/eventPlugins/ResponderTouchHistoryStore.js

**Comment by larsvinter** [comment]
Hi.

Where do you see the node_modules folder? I looked in the "usual" places but it did not look like I had forgotten to remove it (I can't see it on github, only locally.

**Comment by larsvinter** [comment]
Didn't hear back on this so assume it is solved (I can't see any errors on my side)

**Comment by timomeh** [comment]
I got the same problem. When installing the package, it also installed react-native 0.41 as dependency. (I guess because of the peer dependency?) I'm using RN 0.42.

You don't need those peer dependencies.

**Comment by gablorquet** [comment]
Having the same problem happening
