### ISSUE TITLE
Is it possible to add an icon, like FontAwesome, to text?

### ISSUE THREAD

**Issue by nbastoWM** [larsvinter/react-native-awesome-button#3]
I guess the title says it all.

**Comment by Coolnesss** [comment]
+1

**Comment by larsvinter** [comment]
Hi guys.

Just implemented this in 1.8.2 (in fact you can now pass in any sub-view, so not just an icon). You can pass in styling props to the backgroundStyle to make sure it is nicely centered etc (see the updated Advanced example for how to have a user icon next to a "login" label).

Enjoy...
